### ISSUE TITLE
Stack space overflow when saving widget

### ISSUE THREAD

**Issue by kbroman** [kbroman/qtlcharts#27]
With `iplotMScanone`, I'm getting an error when using `saveWidget`.

Set up:

```r
library(qtl)
library(qtlcharts)
data(grav)
grav <- calc.genoprob(grav, step=1)
grav <- reduce2grid(grav)
phecol <- seq(1, nphe(grav), by=5)
times <- attr(grav, "time")[phecol]
out <- scanone(grav, phe=phecol, method="hk")
eff <- estQTLeffects(grav, phe=seq(1, nphe(grav), by=5), what="effects")
```

Make and save the plot:

```r
tosave <- iplotMScanone(out, effects=eff)
htmlwidgets::saveWidget(tosave, file="tmp.html")
```

I get the error:

```
 Stack space overflow: current size 16777216 bytes.
 Use `+RTS -Ksize -RTS' to increase it.
 Error: pandoc document conversion failed with error 2
```

If I don't include `effects=eff`, I can save the thing fine. Or if I use `selfcontained=FALSE` it's fine.

**Comment by timelyportfolio** [comment]
likely related to https://github.com/ramnathv/htmlwidgets/issues/81

**Comment by kbroman** [comment]
@timelyportfolio You're right; I'm working on trying to find a minimal example and to figure out what's really going on.

**Comment by kbroman** [comment]
[Fixed](https://github.com/ramnathv/htmlwidgets/commit/299010a3747a9f8df37ee9c3fa041deb4ae50b4f) in [htmlwidgets](https://github.com/ramnathv/htmlwidgets), by increasing "stack size" for pandoc (and also allowing control of stack size, through `pandoc.stack.size` option).
