### ISSUE TITLE
Current sizing defaults assume a really big screen

### ISSUE THREAD

**Issue by kbroman** [kbroman/qtlcharts#29]
@timelyportfolio [pointed out on twitter](https://twitter.com/timelyportfolio/status/573875445743095810) that my current defaults assume a big screen.

I should consider the expected size of users' screens.

Maybe use a global environment variable, with some helper functions, to more easily adapt to "normal", "big", and "small" screens?

**Comment by timelyportfolio** [comment]
Well, there might be an easier (but possibly not optimal) way.  I see `iplotScantwo` sort of ignores `height`/`width`.  What others do?  I assume mostly those that contain multiple panels.  I'll try to start by doing a prototype with `iplotScantwo` and add as a constraint that we would like to keep the panels in their same assigned positions.  Then, maybe we can iterate from there.

**Comment by kbroman** [comment]
You're right. Two of the functions (`iplotScantwo` and `iplotRF`) were not written in the cleanest way...started with number of pixels per cell in the heatmap rather than with the size of the heatmap, so they can't deal with height and width in a proper way yet.

**Comment by timelyportfolio** [comment]
As something to try, I used what I consider SVG's superpower ( the [`viewBox`](http://sarasoueidan.com/blog/svg-coordinate-systems/) attribute ) to force the `iplotScantwo` to fit in the `height` and `width` specified in `chartOpts`.  If you want to see it, you can do.

```r
devtools::install_github("timelyportfolio/qtlcharts@feature/fit")

iplotScantwo(out2, grav, pheno.col=32, chartOpts = list(height=400, width = 600) )
```

Like I said it is not optimal, but I have used this trick to force the svg to fit its container if a user manually specifies assuming that if a user manually specifies, they have a reason to do so.

**Comment by kbroman** [comment]
@timelyportfolio thanks; I'll take a look at what you've done.

What I was thinking:
- a default aspect ratio for each plot
- some global environmental variable that says the biggest height and width one might want (with a default for normal-sized screens and helper functions for using a setting for larger, smaller, or custom screens)
- for each plot, combine those to figure out what the height and width should be for that plot, to fit within the screen size

**Comment by timelyportfolio** [comment]
To see the tiny change, here is the [compare link](https://github.com/kbroman/qtlcharts/compare/devel...timelyportfolio:feature/fit)

**Comment by kbroman** [comment]
@timelyportfolio I see what you mean about `viewBox`; I really need to take advantage of that feature of SVGs.

**Comment by timelyportfolio** [comment]
It's a shame that most of the `d3` examples don't demo the `viewBox` attribute, since it is so powerful, but it does require some sacrifices.  See http://meloncholy.com/blog/making-responsive-svg-graphs/ and https://blog.safaribooksonline.com/2014/02/17/building-responsible-visualizations-d3-js/ for more on `d3` + `viewBox`.  `nvd3` and `dimple` also both allow for quasi-responsive charts using this feature.

**Comment by kbroman** [comment]
Revised the default plot sizes, and added a function `setScreenSize()` that gives global control over the defaults within a browser.

Within RStudio, still just fitting to the plot window. Within knitr/R Markdown, going for a default of 1000 pixels wide, but also controlled by `fig.width` and `fig.height`.

Also used @timelyportfolio's `viewBox` idea to provide better control over the size of the plots from `iplotScantwo` and `iplotRF`, so now all plots may be controlled by `height` and `width` in `chartOpts`.
