### ISSUE TITLE
In iplotMScanone, plot points rather than curves

### ISSUE THREAD

**Issue by redsofa** [kbroman/qtlcharts#34]
Is there an easy way to change the LOD curve in the iplotMScanone to be a scatterplot instead of a curve? iplotRF (http://kbroman.org/qtlcharts/example/iplotRF.html) left and right panel index is what I would like but in the iplotMScanone view.

Thanks in advance

**Comment by kbroman** [comment]
Not currently; I'll look into adding this option.

**Comment by redsofa** [comment]
Thank you! Can you provide a hint as to how you would approach this? Would
you use an LOD chart like in iplotRF or would you use some other chart? I
need to come up with something by the end of the week. Where I'm struggling
is the data format that each graph type expects.

Thanks

**Comment by kbroman** [comment]
On mouseover, `plotLodCurve` gets called:

- `mouseover`, [Lines 174-181](https://github.com/kbroman/qtlcharts/blob/master/inst/htmlwidgets/lib/qtlcharts/iplotMScanone_noeff.coffee#L174-L181)
- `plotLodCurve`, [Lines 86-95](https://github.com/kbroman/qtlcharts/blob/master/inst/htmlwidgets/lib/qtlcharts/iplotMScanone_noeff.coffee#L86-L95)

That needs to be replaced with a function that plots the points instead of curves.

**Comment by redsofa** [comment]
Thank you this is exactly where I'm stuck.

From what I can gather, the lodcurve function has some logic to determine X
and Y to draw the curve.

https://github.com/kbroman/qtlcharts/blob/master/inst/htmlwidgets/lib/qtlcharts/iplotMScanone_noeff.coffee#L79-L82

I'm struggling with how I would create a circle with cx and cy attributes.
that would "replace" the lodcurve function. In the lod_data structure,
where would I find or determine X and Y  for each point ?

thanks in advance for your help.

Rene

**Comment by kbroman** [comment]
I think I've got it, but traveling and tight connection between flights and so may not be able to push until late this afternoon.

**Comment by redsofa** [comment]
Thank you very much. I'll keep an eye on the repos.

**Comment by kbroman** [comment]
I have it working in the [devel branch](https://github.com/kbroman/qtlcharts/tree/devel). See [this](https://github.com/kbroman/qtlcharts/commit/6d19fc421c2284ec2e8bee39c736aece3d835e68) and [that](https://github.com/kbroman/qtlcharts/commit/af583095fb879d294f3634f333f832cf3e6a7289) commit.

And then do something like this:
 
    devtools::install_github("kbroman/qtlcharts@devel")
    library(qtlcharts)
    data(grav)
    grav <- calc.genoprob(grav, step=1)
    grav <- reduce2grid(grav)
    phecol <- seq(1, nphe(grav), by=5)
    out <- scanone(grav, phe=phecol, method="hk")
    iplotMScanone(out, chartOpts=list(linecolor="", pointsize=2))

**Comment by redsofa** [comment]
Thank you! I It's working great on my end. I can see how cx and cy are
calculated. I was close but the data structure and mostly coffeescript were
giving me a hard time.  Thank you for responding so quickly.

Rene

**Comment by kbroman** [comment]
I found a bug in what I'd done; fixed on plane but haven't yet pushed.

**Comment by kbroman** [comment]
Okay, I think I've got it.

And yes, @redsofa, sorry about the ugly data structures.

**Comment by redsofa** [comment]
OK thank you.

R.

**Comment by kbroman** [comment]
Merged into [master branch](https://github.com/kbroman/qtlcharts/tree/master).

To plot points rather than curves when you are plotting QTL effects, you need to use options `eff_linecolor` and `eff_pointsize` to change things in the right panel.

    library(qtlcharts)
    grav <- calc.genoprob(grav, step=1)
    grav <- reduce2grid(grav)
    phecol <- seq(1, nphe(grav), by=5)
    times <- attr(grav, "time")[phecol]
    out <- scanone(grav, phe=phecol, method="hk")
    iplotMScanone(out, grav, phe=phecol, times=times,
                  chartOpts=list(linecolor="", eff_linecolor="", pointsize=2, eff_pointsize=2))
