### ISSUE TITLE
Over-plotting of axis and title in Shiny

### ISSUE THREAD

**Issue by simecek** [kbroman/qtlcharts#43]
When I render interactive plots in my R/shiny app and change the input in any way, the new plot is rendered but axis and title are plotted over the old ones like in the figure below.

![screencapture](https://cloud.githubusercontent.com/assets/359539/11080037/81d3bf84-87de-11e5-8c3e-c3923e3b4d9d.jpg)

See minimal example with just two plots: (also https://gist.github.com/simecek/bc27b3365fcb6bc77959)

```
library(shiny)
library(qtlcharts)

server <- function(input, output) {
  output$interactivePlot <- iplot_render({
    x <- rnorm(26) * ifelse(input$graphType == "higher values", 10, 1)
    y <- rnorm(26) * ifelse(input$graphType == "higher values", 10, 1)
    p1 <- iplot(x=x, y=y, indID = LETTERS, 
                chartOpts = list(title = input$graphType))
    return(p1)
  })
}

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      radioButtons("graphType", "Select numbers:", 
                   c("lower values", "higher values"), "lower values")
    ),
    mainPanel(iplot_output("interactivePlot", height=450))
  )
)

shinyApp(ui = ui, server = server)
``` 

I have tried both Chrome and Firefox, using shiny_0.12.2, qtlcharts_0.5-18, htmlwidgets_0.5, R 3.2.2.

**Comment by kbroman** [comment]
It was a [simple fix](https://github.com/kbroman/qtlcharts/commit/edbe1eff2fe3804d786070975c294929df21d1e6) (though there's still a problem of proliferation of tool tip objects).
