### ISSUE TITLE
idotplot - throws error with one group

### ISSUE THREAD

**Issue by raredd** [kbroman/qtlcharts#56]
Hi, I was trying to make a dot plot with only one group, but it gives an error.

```r
n <- 100
g <- sample(LETTERS[1:3], n, replace=TRUE)
y <- rnorm(n, match(g, LETTERS[1:3])*10, 5)
idotplot(g, y)

idotplot(rep_len(1, n), y) ## error
idotplot(rep_len(1:2, n), y) ## ok
```

>dotchart: xcatlabels.length [1] != xcategories.length [undefined]
dotchart: Some x values not in xcategories
panelframe: xticklab.length (1) != xticks.length (undefined)

**Comment by kbroman** [comment]
Thanks for letting me know; I’ll work on fixing it.

**Comment by kbroman** [comment]
The problem seems to be in [d3panels](https://github.com/kbroman/d3panels), in the construction of `xcategories` and `xcatlabels`. If we construct these ourselves, it works:

```r
n <- 100
g <- sample(LETTERS[1:3], n, replace=TRUE)
y <- rnorm(n, match(g, LETTERS[1:3])*10, 5)
idotplot(rep_len(1, n), y, chartOpts=list(xcategories=list(1), xcatlabels=list("A")))
```
